[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "cd build && npm ci --production"  # Install deps in the built JS app
]

[start]
cmd = "node ./build/bin/server.js"  # Run from build directory
